# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:

  - name: pip
    before: |
      pip install --upgrade pip
##################################################
  - name: python
    before: |
      pip install python
      pip install boto3
###################################################
  #######################################
  - name: utils
    before: |
      sudo apt-get install tree
  
  #######################################
  
  ## POWERSHELL VID at 3:07:28 by andrew brown link: https://www.youtube.com/watch?v=c3Cn4xYfxJY&t=9459s
  #configures and installs powershell pwsh https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
  - name: powershell
    before: |
      sudo apt-get update
      sudo apt-get install -y wget apt-transport-https software-properties-common
      source /etc/os-release
      wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      rm packages-microsoft-prod.deb
      sudo apt-get update
      sudo apt-get install -y powershell
  # https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-windows.html
  # pwsh

  ########################################
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: | #makes it read the code below as seperate lines instead of one complete line
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
