#!/usr/bin/env bash

echo "== delete-objects"


set -e


#check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

# List all objects in the bucket
OBJECTS=$(aws s3api list-objects-v2 --bucket "$BUCKET_NAME" --query 'Contents[].{Key:Key}' --output text)

# Check if there are any objects to delete
if [ -z "$OBJECTS" ]; then
    echo "Bucket is empty or does not exist."
    exit 0
fi

# Print and delete each object
for KEY in $OBJECTS; do
    echo "Found object: $KEY"
    echo "Deleting object: $KEY"
    aws s3api delete-object --bucket "$BUCKET_NAME" --key "$KEY"
done

echo "All objects in bucket '$BUCKET_NAME' have been deleted."