#!/usr/bin/env bash

echo "== delete-objects"


set -e


#check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1


aws s3api delete-objects --buckets $BUCKET_NAME

