#!/usr/bin/env bash


##adds object to bucket##

echo "put-object"

#check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

#check for FILENAME prefix
if [ -z "$2" ]; then
    echo "There needs to be a filenameprefix eg. ./bucket my-bucket-name my-filename-prefix"
    exit 1
fi


BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY

#create a temp file touch /tmp/newfile.txt
