#!/usr/bin/env bash
echo "=="
# Exit if command returns a non-zero status
set -e

# where the files will be stored
# all linux systems have a temp directory. That way they'll get cleaned up afterwards

OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove files if they are already in temp dir
rm -r $OUTPUT_DIR

# Create output folder

mkdir -p $OUTPUT_DIR

# generate a random number to determin how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
    # generate a random file name
    FILENAME="$OUTPUT_DIR/file_$i.txt"

    # generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR