#!/usr/bin/env bash

##This script creates and uploads files to an S3 bucket##

echo "== sync"

# Exit if command returns a non-zero status
set -e

#check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

#check for FILENAME prefix
if [ -z "$2" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where the files will be stored
# all linux systems have a temp directory. That way they'll get cleaned up afterwards

OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove files if they are already in temp dir
if [ -d "$OUTPUT_DIR" ] && [ "$(ls -A $OUTPUT_DIR)" ]; then
    rm -r $OUTPUT_DIR
fi

# Create output folder

mkdir -p $OUTPUT_DIR

# generate a random number to determin how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
    # generate a random file name
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    # generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files