#!usr/bin/env python

#import boto
import boto3

print("Listing newest buckets...")
# initialize a session using s3
s3 = boto3.client('s3')

# get list of buckets
response = s3.list_buckets()

##print(type(response))

# extract bucket names and creation date
buckets = response['Buckets']

# Sort buckets by creation date, most recent first
sorted_buckets = sorted(buckets, key=lambda b: b['CreationDate'], reverse=True)

most_recent_bucket = sorted_buckets[0]
print(f'Bucket Name: {most_recent_bucket['Name']}, Creation Date: {most_recent_bucket['CreationDate']}')